### ISSUE TITLE
vscode 控制台好多错误哦

### ISSUE THREAD

**Issue by modifMX** [niudai/VSCode-Zhihu#28]
```
TypeError: Cannot read property 'statusCode' of null
	at t.PasteService.<anonymous> (c:\Users\Yi-ky\.vscode\extensions\niudai.vscode-zhihu-0.2.3\dist\extension.js:663:3021)
	at Generator.next (<anonymous>)
	at a (c:\Users\Yi-ky\.vscode\extensions\niudai.vscode-zhihu-0.2.3\dist\extension.js:663:1842)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:582
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:582
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
6resourceLoader.ts:44 Error: 无法读取文件'c:\Users\Yi-ky\.vscode\extensions\niudai.vscode-zhihu-0.2.3\node_modules\katex\dist\katex.min.css' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'c:\Users\Yi-ky\.vscode\extensions\niudai.vscode-zhihu-0.2.3\node_modules\katex\dist\katex.min.css')
    at _.doReadAsFileStream (fileService.ts:457)
```

比如
TypeError: Cannot read property 'statusCode' of null

![image](https://user-images.githubusercontent.com/8953309/76393075-c2fbdf00-63ad-11ea-8c87-ccea425151f6.png)

**Comment by modifMX** [comment]
这个无法读取文件时打开预览模式，按下 `ctrl+c` 出现的
![image](https://user-images.githubusercontent.com/8953309/76400921-0fe6b200-63bc-11ea-80e5-1fedbed8025b.png)

katex.min.css 缺少也是打开预览模式 关闭 在打开情况下

**Comment by niudai** [comment]
问题已经记录，将在未来版本解决，谢谢支持
